export const ADMIN_TOKEN_KEY="admin_token";
export const ADMIN_API_URL=(process.env.NEXT_PUBLIC_API_URL??"https://api.anilbhimani.com").replace(/\/$/,"");
export type AdminIdentity={id:number;name:string;email:string};
export class AdminApiError extends Error{constructor(message:string,public status:number,public errors?:Record<string,unknown>){super(message);this.name="AdminApiError"}}
export function getAdminToken(){return typeof window==="undefined"?"":sessionStorage.getItem(ADMIN_TOKEN_KEY)??""}
export function clearAdminToken(){if(typeof window!=="undefined")sessionStorage.removeItem(ADMIN_TOKEN_KEY)}
function message(data:Record<string,unknown>,status:number){if(typeof data.message==="string")return data.message;if(data.errors&&typeof data.errors==="object"){const first=Object.values(data.errors as Record<string,unknown>).flat()[0];if(typeof first==="string")return first}if(status===401)return"Your admin session is invalid or has expired.";if(status===403)return"This admin account is not authorized.";if(status===422)return"Please review the submitted information.";if(status===429)return"Too many requests. Please wait and try again.";return status>=500?"The server is temporarily unavailable.":`Request failed (${status}).`}
export async function adminApi<T>(path:string,options:RequestInit={},token?:string):Promise<T>{const headers=new Headers(options.headers);headers.set("Accept","application/json");if(options.body&&!(options.body instanceof FormData)&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const auth=token??getAdminToken();if(auth)headers.set("Authorization",`Bearer ${auth}`);let response:Response;try{response=await fetch(`${ADMIN_API_URL}${path}`,{...options,headers,cache:"no-store"})}catch{throw new AdminApiError("Unable to reach the administration API.",0)}let data:Record<string,unknown>={};try{data=await response.json()}catch{}if(!response.ok)throw new AdminApiError(message(data,response.status),response.status,data.errors as Record<string,unknown>|undefined);return data as T}
export function loginAdmin(email:string,password:string){return adminApi<{admin:AdminIdentity;admin_token:string;expires_at:string}>("/api/admin/login",{method:"POST",body:JSON.stringify({email,password})})}
export function validateAdminSession(token:string){return adminApi<{admin:AdminIdentity;expires_at:string}>("/api/admin/session",{method:"POST"},token)}
export function logoutAdmin(token:string){return adminApi<{success:boolean}>("/api/admin/logout",{method:"POST"},token)}
