"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AdminApiError, adminApi } from "@/lib/admin-api";
import AdminShell from "./AdminShell";
import DashboardSection from "./DashboardSection";
import { useAdminAuth } from "./AdminAuthProvider";
type Mode="comments"|"access"|"visitors"|"security"; type Row=Record<string,unknown>;
const config={comments:{title:"Comments",subtitle:"Moderate public blog discussion.",path:"/api/admin/comments?per_page=100",key:"comments"},access:{title:"Access Requests",subtitle:"Review protected-profile access requests.",path:"/api/admin/access-requests",key:"access_requests"},visitors:{title:"Visitors",subtitle:"Visitor identities represented in access requests.",path:"/api/admin/access-requests",key:"access_requests"},security:{title:"Security / Audit",subtitle:"Active access codes, devices and visitor sessions.",path:"/api/admin/security/sessions",key:"visitor_sessions"}} as const;
const text=(v:unknown)=>v==null?"—":typeof v==="object"?JSON.stringify(v):String(v);
const date=(v:unknown)=>typeof v==="string"&&!Number.isNaN(new Date(v).getTime())?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):text(v);
export default function AdminResourceClient({mode}:{mode:Mode}){
 const c=config[mode],{invalidate}=useAdminAuth(); const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{if(mode==="security"){const[s,d,a]=await Promise.all([adminApi<Record<string,unknown>>("/api/admin/security/sessions"),adminApi<Record<string,unknown>>("/api/admin/security/devices"),adminApi<Record<string,unknown>>("/api/admin/security/access-codes")]);setRows([...(s.visitor_sessions as Row[]||[]).map(x=>({...x,_type:"session"})),...(d.device_authorizations as Row[]||[]).map(x=>({...x,_type:"device"})),...(a.access_codes as Row[]||[]).map(x=>({...x,_type:"access-code"}))])}else{const data=await adminApi<Record<string,unknown>>(c.path);let found=(data[c.key] as Row[])||[];if(mode==="visitors"){const unique=new Map<string,Row>();found.forEach(x=>unique.set(String(x.visitor_id),x));found=[...unique.values()]}setRows(found)}}catch(e){if(e instanceof AdminApiError&&[401,403].includes(e.status)){invalidate();return}setError(e instanceof Error?e.message:"Unable to load this section.")}finally{setLoading(false)}},[c.key,c.path,invalidate,mode]);
 useEffect(()=>{const id=setTimeout(()=>void load(),0);return()=>clearTimeout(id)},[load]);
 async function action(row:Row,name:string){if(!row.id)return;let path="",body:BodyInit|undefined;if(mode==="comments"){path=`/api/admin/comments/${row.id}/${name}`;if(name==="reject")body=JSON.stringify({reason:prompt("Optional rejection reason:")||null})}else if(mode==="access"){path=`/api/admin/access-requests/${row.id}/${name}`;if(name==="reject"){const reason=prompt("Rejection reason:");if(!reason?.trim())return;body=JSON.stringify({reason:reason.trim()})}}try{await adminApi(path,{method:"POST",body});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed.")}}
 const display=useMemo(()=>rows.map(row=>({row,name:text(row.visitor_name||((row.visitor as Row|undefined)?.display_name)||row.title||row._type||`#${row.id}`),email:text(row.visitor_email||((row.visitor as Row|undefined)?.email)||row.email),detail:mode==="comments"?text(row.body):mode==="security"?text(row.browser_name||row.device_type||row.ip_address||row.status):text(row.purpose_category||row.relation_category||row.status),status:text(row.status||row._type),when:date(row.created_at||row.requested_at||row.started_at||row.updated_at)})),[mode,rows]);
 return <AdminShell title={c.title} subtitle={c.subtitle} activeHref={mode==="access"?"/admin/access-requests":`/admin/${mode}`}><DashboardSection title={c.title} description="Live data from the Laravel administration API">{loading?<div className="adx-loading"><span className="adx-spinner"/>Loading…</div>:error?<div className="adx-alert"><span>{error}</span><button onClick={()=>void load()}>Retry</button></div>:!display.length?<div className="adx-empty">No records found.</div>:<div className="adx-table-wrap"><table className="adx-table"><thead><tr><th>Name</th><th>Email / detail</th><th>Status</th><th>Date</th>{mode==="comments"||mode==="access"?<th>Actions</th>:null}</tr></thead><tbody>{display.map(({row,name,email,detail,status,when})=><tr key={`${mode}-${String(row._type??"record")}-${String(mode==="visitors"?row.visitor_id:row.id)}-${name}-${when}`}><td className="adx-cell-title">{name}</td><td><strong>{email}</strong><br/><span>{detail}</span></td><td><span className={`adx-pill ${status}`}>{status}</span></td><td>{when}</td>{mode==="comments"?<td><button onClick={()=>void action(row,"approve")}>Approve</button> <button onClick={()=>void action(row,"reject")}>Reject</button></td>:mode==="access"?<td>{status==="pending"?<><button onClick={()=>void action(row,"approve")}>Approve</button> <button onClick={()=>void action(row,"reject")}>Reject</button></>:status==="approved"?<button onClick={()=>void action(row,"revoke")}>Revoke</button>:null}</td>:null}</tr>)}</tbody></table></div>}</DashboardSection></AdminShell>}
